# Generated by Django 4.1.6 on 2024-06-23 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Изображения профиля')),
                ('date_of_birth', models.DateField(help_text='*', verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер телефона')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телеграм')),
                ('whatsapp', models.CharField(blank=True, max_length=100, null=True, verbose_name='WhatsApp')),
                ('vk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вконтакте')),
                ('address', models.TextField(help_text='*', verbose_name='Адрес')),
                ('fio_parents', models.TextField(help_text='*', verbose_name='ФИО родителей')),
                ('parents_place_work', models.TextField(blank=True, null=True, verbose_name='Место работы родителей')),
                ('educational_institution', models.TextField(help_text='*', verbose_name='Образовательное учреждение (школа, класс, ФИО классного руководителя, номер телефона)')),
                ('time_school', models.TextField(help_text='*', verbose_name='Время начала и окончания учебных занятий в школе')),
                ('outside_club', models.TextField(help_text='*', verbose_name='Дополнительные занятия вне клуба (кружки, секции); время')),
                ('hobby', models.TextField(help_text='*', verbose_name='Хобби и увлечения')),
                ('sports', models.TextField(help_text='*', verbose_name='Виды спорта больше всего нравятся ребёнку')),
                ('about_club', models.TextField(help_text='*', verbose_name='Откуда узнали про клуб')),
                ('goals_season', models.TextField(help_text='*', verbose_name='Цели на сезон')),
                ('participation_competition', models.CharField(help_text='*', max_length=50, verbose_name='Участие в соревнованиях')),
                ('wishes', models.TextField(blank=True, null=True, verbose_name='Пожелания')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
