# Generated by Django 5.1.1 on 2024-09-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='directions',
            field=models.ManyToManyField(to='users.trainingdirections', verbose_name='Направления'),
        ),
    ]
