# Generated by Django 5.0.6 on 2024-07-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='Номер телефона'),
        ),
    ]
