# Generated by Django 5.0.6 on 2024-08-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(default=3, verbose_name='Кол-во баллов профиля'),
        ),
    ]
