# Generated by Django 5.0.6 on 2024-08-02 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileadmin',
            options={'verbose_name': 'тренера', 'verbose_name_plural': 'Тренерский состав'},
        ),
    ]
