# Generated by Django 5.0.6 on 2024-07-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='participation_competition',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], help_text='*', max_length=3, verbose_name='Участие в соревнованиях'),
        ),
    ]
