import os

from dotenv import load_dotenv

load_dotenv()

PROJECT_SECRET_KEY = os.getenv("PROJECT_SECRET_KEY")
PROJECT_DEBUG = os.getenv("PROJECT_DEBUG")

CONFIG__SECURE_SSL_REDIRECT = os.getenv("CONFIG__SECURE_SSL_REDIRECT") == "True"
CONFIG__SECURE_HSTS_SECONDS = int(os.getenv("CONFIG__SECURE_HSTS_SECONDS", 0))
CONFIG__SESSION_COOKIE_SECURE = os.getenv("CONFIG__SESSION_COOKIE_SECURE") == "True"
CONFIG__SESSION_COOKIE_AGE = int(os.getenv("CONFIG__SESSION_COOKIE_AGE"))
CONFIG__CSRF_COOKIE_SECURE = os.getenv("CONFIG__CSRF_COOKIE_SECURE") == "True"
CONFIG__SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv("CONFIG__SECURE_HSTS_INCLUDE_SUBDOMAINS") == "True"
CONFIG__SECURE_HSTS_PRELOAD = os.getenv("CONFIG__SECURE_HSTS_PRELOAD") == "True"

PROJECT_EMAIL_HOST_USER = os.getenv("PROJECT_EMAIL_HOST_USER")
PROJECT_EMAIL_HOST_PASSWORD = os.getenv("PROJECT_EMAIL_HOST_PASSWORD")

PROJECT_DOMAIN_NAME = os.getenv("PROJECT_DOMAIN_NAME")

DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASS = os.getenv("DB_PASS")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_OPTIONS = os.getenv("DB_OPTIONS")
