# Generated by Django 5.0.6 on 2024-07-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_coach', models.ImageField(upload_to='coach_images/', verbose_name='Изображения тренера')),
                ('name', models.CharField(max_length=20, verbose_name='Имя тренера')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия тренера')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество тренера')),
                ('directions', models.CharField(max_length=50, verbose_name='Направления')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'тренера',
                'verbose_name_plural': 'Тренерский состав',
            },
        ),
    ]
