# Generated by Django 5.0.6 on 2024-08-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskUser',
        ),
    ]
