# Generated by Django 5.1.1 on 2024-09-05 08:39

from django.db import migrations, models
from app.mainapp.base_mixins import StrMixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_news', models.ImageField(upload_to='news_images/')),
                ('title', models.CharField(max_length=100, verbose_name='Новостной заголовок')),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
            bases=(StrMixin, models.Model),
        ),
    ]
