# Generated by Django 5.1.2 on 2024-11-04 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Изображения профиля')),
                ('phone', models.CharField(blank=True, max_length=110, null=True, verbose_name='Номер телефона')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телеграм')),
                ('vk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вконтакте')),
                ('address', models.TextField(help_text='*', verbose_name='Домашний адрес')),
                ('parents_place_work', models.TextField(blank=True, null=True, verbose_name='Ваше место работы')),
                ('children', models.ManyToManyField(related_name='parents', to='users.profile', verbose_name='Дети')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
