# Generated by Django 5.1.2 on 2024-11-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profileparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileparent',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='parents', to='users.profile', verbose_name='Дети'),
        ),
    ]
