# Generated by Django 5.1.2 on 2024-12-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profileparent_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(help_text='*', verbose_name='Домашний адрес'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fio_parents',
            field=models.TextField(help_text='*', verbose_name='ФИО и номер телефона родителей'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sports',
            field=models.TextField(help_text='*', verbose_name='Любимые виды спорта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wishes',
            field=models.TextField(blank=True, null=True, verbose_name='Пожелания к тренировочному и организационному процессу в клубе'),
        ),
    ]
