# Generated by Django 5.1.2 on 2025-02-07 11:17

import app.mainapp.base_mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_address_alter_profile_fio_parents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Направление персонала')),
            ],
            options={
                'verbose_name': 'направление персонала',
                'verbose_name_plural': 'Направления персонала',
            },
            bases=(app.mainapp.base_mixins.StrMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='profileparent',
            options={'verbose_name': 'Профиль родителя', 'verbose_name_plural': 'Профиль родителей'},
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='profileadmin',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='profileparent',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='directions',
            field=models.ManyToManyField(to='users.trainingdirections', verbose_name='Направления тренировок'),
        ),
        migrations.AddField(
            model_name='profileadmin',
            name='admin_personal',
            field=models.ManyToManyField(blank=True, to='users.administrationperson', verbose_name='Направления персонала'),
        ),
    ]
