# Generated by Django 5.1.1 on 2024-09-05 08:39

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models

from app.mainapp.base_mixins import StrMixin


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Описание тренировки')),
                ('start_time', models.TimeField(verbose_name='Начло в')),
                ('end_time', models.TimeField(verbose_name='Конец в')),
                ('days_of_week', models.CharField(blank=True, max_length=50, verbose_name='Дни недели на весь год')),
                ('elem_color',
                 colorfield.fields.ColorField(default='#0d6dfd7f', image_field=None, max_length=50, samples=None,
                                              verbose_name='Цвет в расписании')),
                ('coaches', models.ManyToManyField(blank=True, related_name='events', to='users.profileadmin',
                                                   verbose_name='Тренер (ы)')),
                ('name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              to='users.trainingdirections', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'тренировки',
                'verbose_name_plural': 'Тренировки',
            },
            bases=(StrMixin, models.Model),
        ),
    ]
