# Generated by Django 5.1.2 on 2024-12-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedules', '0002_cancelevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('schedules_training', 'Расписания'), ('competition', 'Мероприятие')], default='schedules_training', max_length=20, verbose_name='Тип события'),
        ),
    ]
