# Generated by Django 5.1.2 on 2024-12-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedules', '0003_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата мероприятия (Указывать если выбран тип - Мероприятие)'),
        ),
    ]
