# Generated by Django 5.1.2 on 2024-12-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedules', '0004_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='competition_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название мероприятия'),
        ),
    ]
