# Generated by Django 5.1.2 on 2025-02-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedules', '0005_event_competition_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'тренировку или событие', 'verbose_name_plural': 'Тренировки и события'},
        ),
    ]
