# Generated by Django 5.1.1 on 2024-09-03 21:34

import django.db.models.deletion
import mainapp.base_mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_task', models.SmallIntegerField(choices=[(0, 'Новая'), (1, 'В работе'), (2, 'На проверке'), (3, 'Выполнено')], default=0, verbose_name='Статус задачи')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Названия задачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описания')),
                ('estimation_task', models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_tasks', to='users.profileadmin', verbose_name='Инициатор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Выполняющий')),
            ],
            options={
                'verbose_name': 'Задания',
                'verbose_name_plural': 'Задачи',
            },
            bases=(mainapp.base_mixins.StrMixin, models.Model),
        ),
    ]
