# Generated by Django 5.0.6 on 2024-08-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskuser',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описания'),
        ),
        migrations.AddField(
            model_name='taskuser',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Названия задачи'),
        ),
    ]
