# Generated by Django 5.0.6 on 2024-07-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Направления тренировки')),
                ('title', models.CharField(max_length=200, verbose_name='Описания тренировки')),
                ('start_time', models.TimeField(verbose_name='Начло в')),
                ('end_time', models.TimeField(verbose_name='Конец в')),
                ('days_of_week', models.CharField(blank=True, max_length=50, verbose_name='Дни недели на весь год')),
                ('coaches', models.ManyToManyField(blank=True, related_name='events', to='mainapp.coach', verbose_name='Тренер (ы)')),
            ],
            options={
                'verbose_name': 'тренировки',
                'verbose_name_plural': 'Тренировки',
            },
        ),
    ]
