# Generated by Django 5.0.6 on 2024-08-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_schedules', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='events', to='users.profileadmin', verbose_name='Тренер (ы)'),
        ),
    ]
