# Generated by Django 5.0.6 on 2024-07-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancelled_dates',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Отмененные дни'),
        ),
    ]
