# Generated by Django 5.0.6 on 2024-07-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedules', '0001_initial'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'тренировки', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='coaches',
            field=models.ManyToManyField(related_name='events', to='mainapp.coach', verbose_name='Тренер (ы)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='days_of_week',
            field=models.CharField(blank=True, max_length=50, verbose_name='Дни недели на весь год'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(verbose_name='Конец в'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Направления тренировки'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(verbose_name='Начло в'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Описания тренировки'),
        ),
    ]
