# Generated by Django 5.0.6 on 2024-07-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedules', '0002_alter_event_options_remove_event_description_and_more'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='events', to='mainapp.coach', verbose_name='Тренер (ы)'),
        ),
    ]
