# Generated by Django 5.0.6 on 2024-07-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedules', '0002_event_cancelled_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cancelled_dates',
        ),
    ]
