# Generated by Django 5.0.6 on 2024-07-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedules', '0003_alter_event_coaches'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coaches',
            field=models.ManyToManyField(blank=True, default=None, related_name='events', to='mainapp.coach', verbose_name='Тренер (ы)'),
        ),
    ]
