# Generated by Django 5.0.6 on 2024-07-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedules', '0003_remove_event_cancelled_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='elem_color',
            field=models.CharField(default='#0d6dfd7f', max_length=50, verbose_name='Цвет в расписании'),
        ),
    ]
