# Generated by Django 5.0.6 on 2024-07-31 22:39

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedules', '0004_event_elem_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='elem_color',
            field=colorfield.fields.ColorField(default='#0d6dfd7f', image_field=None, max_length=50, samples=None, verbose_name='Цвет в расписании'),
        ),
    ]
